#! /usr/bin/env python

import sys
import re
from optparse import OptionParser

verbose = False
port_list = []


def parse_options():
    global verbose

    parser = OptionParser(
        "Usage: nPorts ")

    parser.add_option('-v', "--verbose", action="store_true",
                      dest="verbose", default=False, help="stdout nmap results")

    (options, args) = parser.parse_args()

    if options.verbose:
        verbose = True


if __name__ == "__main__":
    parse_options()

    for cmd_input in sys.stdin:

        line = cmd_input
        if verbose:
            print(line.strip())
        port = re.findall('[0-9]+/', line)
        if len(port) > 0:
            p_var = int((port[0]).split('/')[0])
            if p_var not in port_list:
                port_list.append(p_var)

    port_list.sort()
    ports = ','.join(str(i) for i in port_list)

    if verbose:
        print('\nports list : '+ports)
    else:
        print('ports list : '+ports)
        

